# Generated by Django 5.2.4 on 2025-10-23 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0003_referenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to='image_gen.users'),
        ),
    ]
