from rest_framework import status

USER_TYPE = (
    ('user', 'USER'),
    ('admin', 'ADMIN'),
)

FAIL = 0
SUCCESS = 1
EMAIL_SUCCESS=2
INVALID_KEYS=3

DEFAULT_MODEL_NAME = 'gpt-3.5-turbo'
DEFAULT_MODEL = 'openai'

HTTP_OK = status.HTTP_200_OK
HTTP_CREATED = status.HTTP_201_CREATED
HTTP_ACCEPTED = status.HTTP_202_ACCEPTED
HTTP_NO_CONTENT = status.HTTP_204_NO_CONTENT
HTTP_BAD_REQUEST = status.HTTP_400_BAD_REQUEST
HTTP_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
HTTP_FORBIDDEN = status.HTTP_403_FORBIDDEN
HTTP_NOT_FOUND = status.HTTP_404_NOT_FOUND
HTTP_CONFLICT = status.HTTP_409_CONFLICT
HTTP_UNPROCESSABLE_ENTITY = status.HTTP_422_UNPROCESSABLE_ENTITY
HTTP_TOKEN_EXPIRED = 498
HTTP_INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
HTTP_NOT_IMPLEMENTED = status.HTTP_501_NOT_IMPLEMENTED
HTTP_BAD_GATEWAY = status.HTTP_502_BAD_GATEWAY
HTTP_SERVICE_UNAVAILABLE = status.HTTP_503_SERVICE_UNAVAILABLE
